name: ğŸ“º Backend

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Trigger the workflow on push to the main
  push:

  # Trigger the workflow on pull request
  pull_request:

jobs:
  ci-pipeline:
    name: ğŸ‘Œ CI - Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20]
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: ğŸ  Checkout code
        uses: actions/checkout@v4

      - name: ğŸº Prepare - Set up Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: ğŸ’» Install Node.js dependencies
        run: npm ci

      - name: ğŸ“ ESLint - Code Linting
        run: npm run lint

      - name: ğŸ—ï¸ Build - Compile Code
        run: npm run build

      - name: ğŸ§ª Tests - Run Unit Tests
        run: npm run test
